### ISSUE TITLE
Back button listener

### ISSUE THREAD

**Issue by xrofa** [NoriginMedia/Norigin-Spatial-Navigation#10]
Hey there! Great library!

Just one question, how would you implement the back button listener?

I was looking at what the lib provides but didn't find any mention of what could we do to handle the back navigation.

**Comment by kajetan-intive** [comment]
That depends what you want to do with back button handler.
Do you want to create some sort of breadcrumb mechanism combining both focusing elements as well as going back according to browser history API?

**Comment by asgvard** [comment]
Hi!

Back Button is a very complicated topic tbh. It can perform a lot of different things such as: navigating to the previous page, hide player controls, focus previous element, scroll to top, focus menu etc.. Such things should be handled manually for each application based on the UX flow, since it's not directly related to the "spatial navigation" as such.
What is the specific scenario you are attempting to solve with the back button?

**Comment by lcaprini** [comment]
HI all, I would like to resume this topic because I have a similar issue on my React tv app.

My app has a lot of different pages but I'm not using react router to navigate them, because I don't want to destroy and recreate them on every navigation, but I want to manage them as a stack, like a mobile/tablet app.

Actually I used React Context API to create a very simple Router that manages an array of ReactElement with very simple push and pop actions; every page wrap all its content in a specific `FocusContext.Provider` with `isFocusBoundary` enabled, and calls `focusSelf()` at the beginning. In that way I can push a page `B` on top on another page `A` and move the focus only in the `B`'s tree.

My problem is related to the pop action. When I pop out `B`, I would like to set the focus on last element in `A`; I tried to manually execute `focusSelf()` inside `A` and all works fine, but I can't do that "automatically" on back.

Any suggestions?

Thanks.

**Comment by zemlanin** [comment]
@lcaprini I've started solving the same problem by putting pressed element's `focusKey` into `history.state` and setting parent's `preferredChildFocusKey` to that value, but…

Since default `focusKey` is steadily incrementing during application runtime, if you'll do re-render of a previous view, all old elements will have new `focusKey`s, so `preferredChildFocusKey` won't get rendered until page reload (or unless you'll generate and explicitly pass `focusKey` to `useFocusable`)

So, possible solutions (none of which I've tried (it's Friday evening and I'm tired)):
- manually generate `focusKey` for _everything_ that can navigate you to another page, and when navigating store `focusKey` for a future use as `preferredChildFocusKey`
- when navigating, store some internal ID (for example, `${group.id}:${thing.id}`), use some constant `focusKey` (for example, `focusKey: 'BACK_NAVIGATION_FOCUS_RESTORE'`) when rendering the JSX for that thing, and have `preferredChildFocusKey: 'BACK_NAVIGATION_FOCUS_RESTORE'` 

Also, maybe `useFocusable` hook could have some options for `focusKey` prefixes that would reset ID counter when changed?..
