### ISSUE TITLE
Compatibility with WebView in AndroidTV

### ISSUE THREAD

**Issue by linasmk** [NoriginMedia/Norigin-Spatial-Navigation#112]
**Is your feature request related to a problem? Please describe.**
It's mentioned in your docs that your spatial navigation works on all web-based platforms such as browser and smart TVs. However, when it comes to Android TV, you mention only the React Native solution, although Android has its own Web View and to my limited understanding it should work based on the same principles as Tizen and WebOS...

**Describe the solution you'd like**
Sorry if I misunderstood something, but before starting to apply your solution to web-based TVs, I would like to hear more on why Android Web View is not included among the supported platforms like Tizen, WebOS and Vidaa?

And if this is the case, could you please broaden my imperfect understanding why Norigin spatial navigation cannot be applied to Android Web View?

**Comment by predikament** [comment]
Hello @linasmk, thanks for getting in touch.

The reasoning for this is quite simple: We do not explicitly support it because we do not develop or test using this solution.

I do not see any _obvious_ reasons why this library should not work with Android WebView, however  cannot offer any guarantees that it will either.

The Android WebView is just another embedded browser view which on the different OS versions and flavors usually equates to either a single process Chromium or WebKit variant from what I remember, so it is still a browser and thus there is no obvious reason why it should not be compatible.

You can be the first one to try it out! Best of luck to you. 

I will close this now as it is not an issue per se.
