### ISSUE TITLE
Vertically stacked items focus issue

### ISSUE THREAD

**Issue by hhanifkhan** [NoriginMedia/Norigin-Spatial-Navigation#125]
**Describe the bug**
Case 1: Focus Skipping
- I have 4 vertically stacked items.
- Using up and down arrow keys, focus skips the 3rd item, moving directly from the 2nd to the 4th item.

Case 2: Non-Focusable Element
Even setting the 3rd item's width to 100%, it remains non-focusable.

**To Reproduce**
1. Go to [source_url](https://codesandbox.io/p/sandbox/eloquent-dijkstra-txnfpc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrivbplw00063b6lu5vf6uwr%2522%252C%2522sizes%2522%253A%255B90%252C10%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrivbplw00023b6lgybrr8em%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrivbplw00033b6lc18ajfeh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrivbplw00053b6l5fnkxwzk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40.93432361904414%252C59.06567638095586%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrivbplw00023b6lgybrr8em%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrivbplw00013b6lywu4s9a3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clriveubu00673b6lkvm1n8m8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrivbplw00023b6lgybrr8em%2522%252C%2522activeTabId%2522%253A%2522clriveubu00673b6lkvm1n8m8%2522%257D%252C%2522clrivbplw00053b6l5fnkxwzk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrivbplw00043b6lcwaw3unu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrivbplw00053b6l5fnkxwzk%2522%252C%2522activeTabId%2522%253A%2522clrivbplw00043b6lcwaw3unu%2522%257D%252C%2522clrivbplw00033b6lc18ajfeh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrivbplw00033b6lc18ajfeh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected behavior**
Focus should move sequentially through all four items using up and down arrow keys.
The 3rd item should be focusable.

**Screenshots**
attaching video

https://github.com/NoriginMedia/Norigin-Spatial-Navigation/assets/12639420/c0e0f066-5698-44f6-b977-ec50e41abedb

**Additional context**

**Comment by asgvard** [comment]
Hi!

Thanks for the good description of the issue you are facing.

We have a logic in our algorithm that considers the item as Main Axis Sibling when its edge overlaps with the current item by at least `20%` (you can check for the usage of this constant: https://github.com/NoriginMedia/Norigin-Spatial-Navigation/blob/19ceeb15bf3078ed6f995ae211116595aabffd11/src/SpatialNavigation.ts#L33). Otherwise it would jump sideways for items that overlap for at least 1px, which is what we tried to avoid by doing this check. In your case the problem is that the item on row 3 is too far left, so visually the item from row 4 "looks closer".
It seems to be quite an edge case and I'm not sure we want to change the algorithm because there will be other edge cases that might break due to this. I assume this is some kind of EPG grid based on the layout you provided?

We might look into letting users customize the Adjacent Threshold, but for now you can consider the next workaround:
1) Set predictive focus keys for all items (for example as `my-item-{rowIndex}-{columnIndex}`)
2) Block default navigation by returning `false` from `onArrowPress` ([Docs](https://tv2norge.atlassian.net/wiki/spaces/AI/pages/5560992142/Next+API+Documentation#How-to-handle-old-vs-new-functionality%3F))
3) Manually call setFocus to the desired item Index like `my-item-{rowIndex + 1}-{columnIndex}` if it goes Down for example.

I hope it answers your question. We will add a task to our backlog to see if we can provide more control for users to decide the distance calculations strategy, but it's unlikely to be a high priority as there is a way to override this behavior.
