### ISSUE TITLE
Navigating over the elements be skipping the elements

### ISSUE THREAD

**Issue by kartikKarekarGSLAB** [NoriginMedia/Norigin-Spatial-Navigation#15]
Hello all,

I have integrated this library with my react application. I have designed a grid view where I have added the Focus Container and also added each element from the grid as a Leaf Focusable component. I have added all the required configurations as well. But the behavior is skipping the focus over the third element when the focus moved from left to right and the same when the navigation started from right to left it skipping the second element. (Considering the grid has 4 columns)

Please find the code snippet as below,

`
const RibbonRowContent = function ({ ribbonContentList, onAssetPress, onAssetFocus }: RibbonRowContentProperties) {
    const { ref, focusKey } = useFocusable({});
    return (
        <FocusContext.Provider value={focusKey}>
            <ContentRowScrollingWrapper ref={ref}>
                {ribbonContentList.map((element: any) => (
                    <RibbonAsset
                        key={element.videoId}
                        assetDetails={element}
                        onEnterPress={onAssetPress}
                        onFocus={onAssetFocus}
                    />
                ))}
            </ContentRowScrollingWrapper>
        </FocusContext.Provider>
    );
};
`

Please let me know how I can resolve this issue, since similar kind of behaviour getting for the Navigation Drawer Menu integrated.

**Comment by LynchyC** [comment]
@kartikKarekarGSLAB Is it possible to ask what styling do you have applied to the focusable components? 

This library does take the positioning of the rendered elements into account and something that go against the document flow may cause an element to be overlooked by the spatial navigation.

**Comment by kartikKarekarGSLAB** [comment]
HI @asgvard ,

Please find the structure below,
`<FocusContext.Provider value={focusKey}>
            <ContentRowScrollingWrapper ref={ref}>
                {ribbonContentList.map((element: any) => (
                    <RibbonAsset
                        key={element.Id}
                        assetDetails={element}
                        onEnterPress={onAssetPress}
                        onFocus={onAssetFocus}
                    />
                ))}
            </ContentRowScrollingWrapper>
        </FocusContext.Provider>`

Here the ContentRowScrollingWrapper having style as,
`overflow-x: hidden;
    overflow-y: auto;
    display: flex;
    flex-direction: row;
    margin-bottom: 1vh;`
    
    And the ribbon element having style as,
    
   `display: flex;
    flex-direction: column;`
    
    Inside which each element is the Material UI's ImageListItem element.
    
    For the implementation followed the below example from the Material UI library,
    - https://mui.com/material-ui/react-image-list/
    From which only the 'ImageListItem'  element is used.

**Comment by asgvard** [comment]
Hi @kartikKarekarGSLAB 
It is a bit hard to spot the issue here, without seeing the full example or logs with "debug" and "visualDebug", especially when external UI libraries are used.
Would it be possible to create a Sandbox example or a Github repo where the issue can be clearly reproduced?
So far I cannot see anything obvious that would cause this.
The only styling consideration is to make sure the elements are not overlapping each other.

**Comment by kartikKarekarGSLAB** [comment]
Hi @asgvard ,

Please find the below git hub repo for the same,
- https://github.com/kartikKarekarGSLAB/TV-application-demo

**Comment by predikament** [comment]
Hello @kartikKarekarGSLAB.

I have run your project locally and looked into your issue, which I can also reproduce. 

After investigating for a bit I am quite confident that this issue with it skipping items is happening due to what was [mentioned earlier in this thread](https://github.com/NoriginMedia/Norigin-Spatial-Navigation/issues/15#issuecomment-1148705573): 
> If the items overlap at least by 1 px, it will make it skip through items.

When I resized my view-port (because I opened my developer tools embedded inside my browser window) then suddenly no menu ("drawer") items were skipped and the navigation worked as you intend it to.

You'll need to find a way to not make these elements overlap each other, otherwise the library has no means to understand what the next intended element is. 

Best of luck to you and happy coding!

**Comment by kartikKarekarGSLAB** [comment]
Thank you @asgvard , @predikament for the help and follow-up for the same.

I will check the styling issues for the same.

I request you both to add some pointers in the documentation page of the library for the points to be considered while adding the navigation library for any application, that will be really helpful.
