### ISSUE TITLE
Compiling for WebOS LG Question

### ISSUE THREAD

**Issue by titus-shoats** [NoriginMedia/Norigin-Spatial-Navigation#26]
I recently left a question and I think there was a misunderstanding. Is there any commands to compile the example source demo into a webos project. Like some other ReactTV Projects have commands (react-tv-cli  -webos). Im very familiar with building apps for tv, but I'm not sure how to get this to compile for WebOS. Any advice? Thanks so much..

**Comment by predikament** [comment]
Hello again @titus-shoats! 

> I recently left a question and I think there was a misunderstanding.

I was the one who replied to and closed your previous issue. Let's try again. ☺️

> Is there any commands to compile the example source demo into a webos project. Like some other ReactTV Projects have commands (react-tv-cli -webos). Im very familiar with building apps for tv, but I'm not sure how to get this to compile for WebOS. Any advice? Thanks so much..

Unfortunately We do not maintain demo-builds for all platforms, as it would be a massive overhead.

Running the demo project on a WebOS TVs should however be relatively straightforward (especially if you have past experience with the platform):
- Check out this repository
- Install its dependencies
- Add a dev-server configuration (in _webpack.config.dev.js_) to define the `host` / `port` you intend to serve it from:
```javascript
devServer: {
    host: 'MY.PUBLIC.NETWORK.IP' // An IP that the TV you intend to use can actually reach
    port: 1234 // If you want to serve it on a different port (Default: 3000)
  }
```
(This is to ensure it can be reached and loaded externally, i.e. from your TV.)
- Define a target in Webpack to ensure the library is transpiled and can run on your intended device 
```javascript
target: ['es5']
```
(This is usually needed because this library is not pre-transpiled and the ES support is quite varying across the different TV model-years, so it's better to ensure it's transpiled to something that works everywhere for you.)
- Run the development build script: https://github.com/NoriginMedia/Norigin-Spatial-Navigation/blob/main/package.json#L12
- Point your WebOS application to where the demo is served from and run it

Hope you figure it out. Happy coding!

**Comment by titus-shoats** [comment]
This is exactly what I was looking for thanks so much!

**Comment by predikament** [comment]
> This is exactly what I was looking for thanks so much!

Happy to hear that! 

I will close this issue then. Happy coding! <img src="https://cdn.betterttv.net/emote/630a77988d5463737706539a/3x" width="32px" height="32px">
