### ISSUE TITLE
Nodes not focusable anymore after hot reload

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [NoriginMedia/Norigin-Spatial-Navigation#37]
**Describe the bug**
In a [Vite.js](https://vitejs.dev/) live reload environment, focusable elements are not focusable anymore after hot reloading the component.

**To Reproduce**
1. Init a simple Vite.js project
2. Add the Norigin Spatial Navigation library
3. Add a simple component that uses `useFocusable`
4. Run the project
5. Make a change to the component

**Expected behavior**
After a hot reload, the component should still be focusable.

**Additional context**
Not sure if it is Vite.js specific. Perhaps it can be reproduced in Webpack as well.

I've cloned and linked the repo to do some debugging and found that the `useEffectOnce` is the culprit. After a hot reload, the useEffect is triggered which removes the node from the registry. But the `effectCalled` ref isn't cleared, so the node never gets added again.

**Comment by predikament** [comment]
Hello @ChristiaanScheermeijer, thanks for opening an issue.

We are not actively using Vite ourselves, but are sorry to hear there's such an issue happening.

> I've cloned and linked the repo to do some debugging and found that the useEffectOnce is the culprit. After a hot reload, the useEffect is triggered which removes the node from the registry. But the effectCalled ref isn't cleared, so the node never gets added again.

If you can think of a solution that would work without having any adverse effects then you could perhaps open a PR?

Otherwise it might take a bit for us to get around to looking into this issue, although we will hopefully resolve it eventually.

Cheers,
@predikament

**Comment by ChristiaanScheermeijer** [comment]
Hi @predikament,

Thanks for looking into this issue. I couldn't reproduce this issue using Webpack, so I've migrated the example application to a Vite.js application here: https://github.com/ChristiaanScheermeijer/spatial-navigation-vite-example

To reproduce the bug, change the `menuItemText` to something different and wait for a hot reload.

Before I can fix this issue, can you explain which problem the `useEffectOnce` solves exactly in what scenario?

**Comment by predikament** [comment]
Hello again,

The `useEffectOnce` hook was added as part of this: https://github.com/NoriginMedia/Norigin-Spatial-Navigation/releases/tag/v1.1.0.

**Comment by predikament** [comment]
Hello @ChristiaanScheermeijer!

I believe I have figured out your issue and I do not think it is at all related to our library actually -
It seems more like an issue related to how you have written your code, in combination with how React + Vite HMR works. 

When checking your project (Thanks again for sending that btw!) I noticed that your `<Text>` component is written as an [anonymous function](https://github.com/ChristiaanScheermeijer/spatial-navigation-vite-example/blob/master/src/Test.tsx#L3):
```javascript
import React from 'react';

export default function() { // <-- Unnamed
  const menuItemText = 'change me!';

  return <div>{menuItemText}</div>;
};
```

So I ran your project and changed your component to this:
```javascript
import React from 'react';

const Text = () => {
  const menuItemText = 'change me!';

  return <div>{menuItemText}</div>;
}

export default Text;
```

And now everything is still focusable and works as intended.. So I think it's more an issue here that there's something with Vite where it does not reload it due to this having been unnamed. 

Regardless of this I would recommend naming your component's export functions, so to have a better / more easily traceable stack-trace for debugging.

Let me know if this is enough feedback for you to mark this issue as resolved. Thanks!

Cheers,
@predikament

**Comment by ChristiaanScheermeijer** [comment]
Hi @predikament,

Thank you for the extensive update! That's a really good find, I hope it didn't cause you too much trouble getting here ✌️ 

I almost feel bad for saying this, but the project where we found the issue, doesn't contain any unnamed components.

But the HMR topic is interesting... perhaps it is something similar causing this issue due to a different problem.

**Comment by predikament** [comment]
> I almost feel bad for saying this, but the project where we found the issue, doesn't contain any unnamed components.

Ah, alright. No worries at all - It was interesting to investigate a bit regardless. 🕵️

> But the HMR topic is interesting... perhaps it is something similar causing this issue due to a different problem.
I would _strongly_ assume that your actual problem is somehow a by-product of this, yes.

There is an open PR with some reworks to Vite's HMR refresh logic here: https://github.com/vitejs/vite/pull/10239

Perhaps you can check that out sometime to see if it resolves the issue you see in your project? Outside of this I am unfortunately out of solutions.

Knowing this behavior with the Vite HMR I don't feel comfortable trying to fix this in our project right away, but will keep it in mind going forward.

Best of luck to you and happy coding! 😸
