### ISSUE TITLE
Can you recommend any package for scrolling like your package?

### ISSUE THREAD

**Issue by siarheipashkevich** [NoriginMedia/Norigin-Spatial-Navigation#52]
Hi all.

Thanks for this package.

Can you recommend any package for scrolling like your package?

**Comment by guilleccc** [comment]
Hi @siarheipashkevich ,

We recommend to use `scrollTo`, as it is indicated in our [example](https://github.com/NoriginMedia/Norigin-Spatial-Navigation/blob/main/src/App.tsx#L286):
```
const onAssetFocus = useCallback(
    ({ x }: { x: number }) => {
      scrollingRef.current.scrollTo({
        left: x,
        behavior: 'smooth'
      });
    },
    [scrollingRef]
  );
```

Since we don't use any specific scrolling library in our apps, I'm unable to recommend a lib for you. It is of course possible to find many libraries for this purpose out there. As long as you set the coordinates(x, y) and scrollRef, all of them should be compatible.
