### ISSUE TITLE
Navigation between rails not happening as expected

### ISSUE THREAD

**Issue by krackjack234** [NoriginMedia/Norigin-Spatial-Navigation#53]
**Describe the bug**
We are using the Norigin Media Spatial Navigation library to handle remote navigation on CTVs.
In this context, we wanted to check why we are seeing the below navigation behaviour

**Goal**

Achieve similar or close to Apple’s TV Navigation behavior

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://github.com/krackjack234/Norigin-Spatial-Navigation/tree/issues/53/Down-Navigation-Not-Working. The code is forked from main branch of norigin media repo where we have made few modifications
2. Build and run the app
3. Click on the DPAD right button of the keyboard to bring focus from the menu to the first rail (TV Channels)
4. Press right to go to the 4th card (Asset 4) in the first rail
5. Press down

**Expected behaviour**
The focus should come to the second card of the 2nd rail (Series) based on the distance of the last focused card (i.e 4th card of first rail i.e.TV Channels rail)

**Actual behaviour**
On pressing down, the focus goes to the 4th card of the 3rd rail (Recommended) completely skipping the 2nd rail.

**Demo Code Changes**

Remove FocusContext.Provider for each of the ContentRow so that all the rows are tested for nearest sibling in a single FocusContext.Provider

**Proposal**  

Expose ADJACENT_SLICE_THRESHOLD , ADJACENT_SLICE_WEIGHT , DIAGONAL_SLICE_WEIGHT or similar so we can configure and achieve different navigation behaviors

**Screenshots**

![Spatial-Navigation-Demo](https://user-images.githubusercontent.com/50735078/207570654-a6e2d508-9f48-4781-8f99-15e59568a097.gif)

**Additional context**
We wanted to check below

1. Why we are seeing this behaviour and how can we override this to ensure the focus goes to the 2nd rail?
2. Currently, we have put all the rails in a single FocusContextProvider so that we can match the Apple tv navigation behaviour. How can we achieve the Apple TV navigation behaviour where on pressing Dpad Up button, the focus always goes to the closest card in the **left** direction instead of in the **right** direction?

Thanks!

**Comment by MacgyverMartins** [comment]
@krackjack234 I just start using this lib and I'm facing some problems too. Let me try to help you with some questions: 

if you press the arrow down when the focus is on the first asset of the first rail, will it focus on the second rail?

Also, do you have some margin distance between the rails? I saw that, if you do not set a margin for focusable components, it could not work well

**Comment by krackjack234** [comment]
@MacgyverMartins  

> if you press the arrow down when the focus is on the first asset of the first rail, will it focus on the second rail?


Yes, if the focus is on the first asset of the first rail then on DPad down, it should go to 2nd rail. If the user has scrolled the 2nd rail and right now say the 5th card in the 2nd rail is below the first card of the first rail, then focus should go to the **5th card of the 2nd rail** (nearest sibling in down direction). This is the expectation.

Note in the example I shared, all the rails are in one single focusable container.

**Comment by MacgyverMartins** [comment]
@krackjack234 hmmmm. I think, you may need to have one FocusContext provider for each rail like [ContentRow on the example code](https://github.com/krackjack234/Norigin-Spatial-Navigation/blob/issues/53/Down-Navigation-Not-Working/src/App.tsx#L269)
I have a similar interface here, and each row/rail has its own FocusProvider as well.

**Comment by krackjack234** [comment]
@MacgyverMartins  if we put each row/rail in a separate FocusProvider, then on pressing down from the 5th card of the 1st rail, the focus will come to the first card of the 2nd rail as the library by default will focus on the first child of a focus tree. This is not what we want and is not the same as Apple TV's navigation behaviour.

**Comment by krackjack234** [comment]
@asgvard, @guilleccc Could you help us to the right direction for this issue?

**Comment by guilleccc** [comment]
Hi @krackjack234 ,

I appreciate you taking the time to explain this issue. Our team has experienced similar issues with navigation between containers, and this is something we'd like to improve with a new feature.
At the moment, the focus goes to the first child (or the last child) in the row. We might need to select the closest child from the "coordinates" of the previous item (in a different row).

Sincerely, we can't promise to work on this improvement any time soon, but we can set it as a high priority based on the number of developers experiencing this problem.

Personally, I would recommend using "FocusContext" for the rows, since the navigation will be more consistent.

**Comment by asgvard** [comment]
Hello.

As you have mentioned, in the demo code you have removed `FocusContext.Provider` for each Row, which makes it try to find the individual closest elements, so that would explain why it goes to the 3rd row. We had experienced similar issues when trying to implement the "grid view", where multiple Rows are treated as a grid, so in the end we ended up just listening to `onArrowPress` to decide the row and the element to go to.
Proper solution would be to have a new feature that would help navigating between multiple Focusable Containers `from a certain coordinate`. So when the algorithm enters new container, it will calculate coordinates starting from a custom point, and not from top-left (default) or focusing the last focused child.
However as it is not a high prio internally, I can't promise when we implement it.
Please keep an eye on the library updates.
