### ISSUE TITLE
`measureLayout` is not exported for using

### ISSUE THREAD

**Issue by siarheipashkevich** [NoriginMedia/Norigin-Spatial-Navigation#59]
Hi all,

Could you please export `measureLayout` for using in our app?

**Comment by predikament** [comment]
Hello @siarheipashkevich.

Thanks for getting in touch with us.

When it comes to `measureLayout`, that is only meant to be used for the service itself, so to allow measuring the elements - As such it should not be used as a client-specific utility function, since that is not the intention.

If you require something with similar functionality I would suggest creating your own utility function that suits your own needs, be it a copy of the internals of `measureLayout`, or some `getBoundingClientRect` variation.

Best of luck to you!
