### ISSUE TITLE
How to replace `LastFocusedChild` for specific container?

### ISSUE THREAD

**Issue by siarheipashkevich** [NoriginMedia/Norigin-Spatial-Navigation#60]
Hi all.

Could you please suggest hot to replace `LastFocusedChild` for specific container when I back to this specific container.

For example: I've the container with children and leave this container on second child, but when I'm going to return to this component I want that the focus will be on fourth child. How I can implement this?

I don't have direct access to the `SpatialNavigationService` for example.

**Comment by asgvard** [comment]
Hi,

I think that in order to solve your situation you could disable saving of the last child for that container with `saveLastFocusedChild: false` and then use `preferredChildFocusKey` prop that you can dynamically update in the parent component to keep track of what should be the next focused child when you return to that container.
Let us know if that suits your use case. Feel free to reopen if you still need help with solving it 👍

**Comment by asgvard** [comment]
In the Service file (for reference), it would try to use `last focused child` first, and then it will go for `preferred child`: https://github.com/NoriginMedia/Norigin-Spatial-Navigation/blob/main/src/SpatialNavigation.ts#L1048
