### ISSUE TITLE
TypeScript Errors

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [NoriginMedia/Norigin-Spatial-Navigation#64]
**Describe the bug**
- `Property 'includes' does not exist on type 'string[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2016' or later.ts(2550)`
- `Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`

**To Reproduce**
1. Clone repo
2. Run `pnpm i`
3. Run `pnpm start`

**Expected behavior**
No TypeScript or Webpack errors

**Screenshots**
![image](https://user-images.githubusercontent.com/52586855/219994518-9cf45190-7b56-46ad-9a97-a9b36b8572d5.png)

**Comment by predikament** [comment]
Hello @ChocolateLoverRaj,

Thanks for your contribution.

I am however not quite sure how you are reproducing these problems - We are several people both working with and using this library on a daily basis and none of us have seen these errors ourselves.

Based on this I am worried this is a change for an issue you are just experiencing locally, likely due to some global npm packages being installed or the like.

Could you please provide the details needed for setting up our the environment to reproduce the issue, so we can confirm these changes are in fact required?

Thanks

**Comment by asgvard** [comment]
According to our `package-lock.json` file, we are using Typescript `4.6.2`. In case you are using other 3rd party package managers such as `pnpm`, it might silently upgrade TS or other dependencies versions and cause such issues. Unfortunately we cannot account for all possible TS versions that developers might have on their local environments and/or installed by different package managers. This problem seems to be related to your local development environment and `pnpm` behavior.
