### ISSUE TITLE
Focused element is not fully visible / scrolled

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [NoriginMedia/Norigin-Spatial-Navigation#66]
**Describe the bug**
Only part of the rectangle is visible

**To Reproduce**
You may need to make the screen height a little smaller to reproduce.

**Expected behavior**
Focused elements should be scrolled completely into view 

**Screenshots**
[Screen recording 2023-02-19 6.24.35 PM.webm](https://user-images.githubusercontent.com/52586855/219995557-2c4e6391-e5ec-4fdd-b29f-ac684897b80a.webm)

**Comment by YoavHortman** [comment]
The functionality of focusing the element on screen is provided by the default behaviour of the browser `scrollTo`.

You might just need to play with the css in the demo to get it to do what you want.

**Comment by predikament** [comment]
Hello @ChocolateLoverRaj.

The embedded application is for demonstrating the library's functionalities, more so than being meant as a boilerplate application for anyone to use as is. (This is since most implementations will differ depending on your intended target devices and screens.)

As such it is not part of the intended scope of our demo.

To not have this issue in your application you could consider several approaches, depending on your designs and intended interactions of course:
1. Make the window resize
1. Make rows dynamically shift on resizing
1. ++ Other solutions

Best of luck to you.
