### ISSUE TITLE
Why stop using "getBoundingClientRect" for layout measurements?

### ISSUE THREAD

**Issue by leonchabbey** [NoriginMedia/Norigin-Spatial-Navigation#9]
In the latest release: https://github.com/NoriginMedia/Norigin-Spatial-Navigation/releases/tag/v1.0.2, you reverted the way it measures the layout/position of the nodes.

So now, if a node moved (ie: css transforms) after its initial rendering, it might not being taken into the potential next focus.
The current logic, as i understand, is that it only checks the siblings of the current node by measuring their layouts again before using the algo to get the next focus node.
However with this logic, if a node in another tree moved and now should "visually" be the next focus (ie: on press arrow right) it might not because maybe it wasnt the next focus using the previous layout measurement.

The current implementation makes sense and has its pros and cons, but i was wondering why the switch?
Did you see real performance issues with `getBoundingClientRect`?

**Comment by asgvard** [comment]
Hi,

yes, indeed, we have initially used the "offsets" in the older implementation of this library.
When migrating to the new hook based library we have changed it to the `getBoundingClientRect`.
However it caused unexpected (to certain extend) side effects such as calculating the coordinates post-CSS transforms, which was not compatible with the most of our UI implementations when it comes to the overlapping elements.

So in order to keep backward compatibility (and to a lesser extend - for the better performance) we decided to roll back to use static "offsets", which are calculated post-CSS transforms.

It might sound counter-intuitive, but our thought was to rely on the static coordinates, while any CSS transform is applied "after" the layout is computed.
It allows to solve certain issues with the overlapping elements. One use case is having Side Menu, that is overlapping the main content. But if we press left - it still opens the Side Menu. In order to achieve this, we have Side Menu to have absolute position outside of the screen (left: -300px; for example), and then translating it back for the same amount with "transform: translateX(300px);". So for the Navigation service, the Side Menu is technically to the left from everything else, but visually it is overlapping the screen.

Another use case is: we have a carousel (row) with a lot of items, when the item is focused it gets scaled up, which makes it overlap the sibling items. When using `getBoundingClientRect` it would skip over the next sibling, because it was "under" the focused item.

So to sum up, and to answer your question, we have relied on the static "offsets" (CSS layout) while also making some tricks with CSS transforms, and we intentionally don't want any CSS transform to affect the coordinates calculation. We will discuss it again, and perhaps make it optional, via init config, such as `useGetBoundingClientRect`.

I'll also leave this link to the spec for the future discussions:
https://www.w3.org/TR/css-transforms-1/#transform-rendering

_Note: Transformations do affect the visual rendering, but have no affect on the CSS layout other than affecting overflow. Transforms are also taken into account when computing client rectangles exposed via the Element Interface Extensions, namely [getClientRects()](https://www.w3.org/TR/cssom-view/#dom-element-getclientrects) and [getBoundingClientRect()](https://www.w3.org/TR/cssom-view/#dom-element-getboundingclientrect), which are specified in [[CSSOM-VIEW]](https://www.w3.org/TR/css-transforms-1/#biblio-cssom-view)._

**Comment by leonchabbey** [comment]
Thanks for the reply!

So yep... none of the "solutions" are perfect and we will have some layout logic issue with any of them. I tried to do something similar to what you said  (-> optional `useGetBoundingClientRect`) in a PR previous to writing this issue and yeah it might be a solution to have something hybrid like this.

**Comment by predikament** [comment]
Question looks to be answered, so I will close this for now. 

@leonchabbey: Please just reopen it with any comments you might have, if you would like to further discuss anything in relation to this.
